### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by ljerka** [swagger-api/swagger-editor#1096]
I'm trying to get the editor to work locally. Followed the instructions on http://swagger.io/swagger-editor/,

> git clone https://github.com/swagger-api/swagger-editor.git
> cd swagger-editor
> npm install
> npm start

On the last command I get an error:

```
D:\Projects\swagger-editor>npm start

> swagger-editor@2.10.4 start D:\Projects\swagger-editor
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1239:19)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Progs\\nodejs\\node.exe" "C:\\Users\\apisit.Apis\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor@2.10.4 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor@2.10.4 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the swagger-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swagger-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls swagger-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\swagger-editor\npm-debug.log
```

node: v.6.7.0
npm: v.3.10.8
OS: win7

**Comment by saharj** [comment]
I don't see this issue. Please try to remove the `node_module` and then `npm install` and `npm start`. This may solve your issue. Please let me know if you still have see this issue

**Comment by ljerka** [comment]
Tried it few times already, still it gives me the same error.

**Comment by DelightedD0D** [comment]
I get the exact same error on windows server 2012. Worked fine on my Mac though :(

**Comment by DelightedD0D** [comment]
@ljerka I think the important bit in the error is:

```
Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1239:19)
```

This error is basically saying that the server could not listen to port 8080 on 127.0.0.1. For me, this was because Apache was already using port 8080 (could also be Skype or some other program for you). 

To fix this, I opened `server.js` and changed line 38 to:

`var PORT = process.env.PORT || 8081;`

All working now :)

**Comment by ljerka** [comment]
@DelightedD0D You are right, changing the port value fixed the problem :)
I'm closing the issue.
