### ISSUE TITLE
Unable to run npm run build on Windows

### ISSUE THREAD

**Issue by bspeer-cs** [swagger-api/swagger-editor#1149]
**Swagger File**

```yaml
 # paste your swagger document here
```

* Version: 2.10.4
* Browser/OS: Firefox 50.1.0 / Windows_NT 10.0.10586

**Issue**
Trying to execute npm run build on Windows.  Get the error

> swagger-editor@2.10.4 clean C:\nodejs\swagger-editor
> rm -rf dist/**

'rm' is not recognized as an internal or external command,
operable program or batch.  

Debug File --
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle swagger-editor@2.10.4~prebuild: swagger-editor@2.10.4
6 verbose lifecycle swagger-editor@2.10.4~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle swagger-editor@2.10.4~prebuild: PATH: C:\nodejs\node_modules\npm\bin\node-gyp-bin;C:\nodejs\swagger-editor\node_modules\.bin;C:\Oracle\11.2.0_client\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Perforce;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\nodejs\;C:\python\Scripts\;C:\python\;C:\Users\bspeer\AppData\Roaming\npm
8 verbose lifecycle swagger-editor@2.10.4~prebuild: CWD: C:\nodejs\swagger-editor
9 silly lifecycle swagger-editor@2.10.4~prebuild: Args: [ '/d /s /c', 'npm run clean' ]
10 silly lifecycle swagger-editor@2.10.4~prebuild: Returned: code: 1  signal: null
11 info lifecycle swagger-editor@2.10.4~prebuild: Failed to exec prebuild script
12 verbose stack Error: swagger-editor@2.10.4 prebuild: `npm run clean`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid swagger-editor@2.10.4
14 verbose cwd C:\nodejs\swagger-editor
15 error Windows_NT 10.0.10586
16 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
17 error node v6.9.4
18 error npm  v3.10.10
19 error code ELIFECYCLE
20 error swagger-editor@2.10.4 prebuild: `npm run clean`
20 error Exit status 1
21 error Failed at the swagger-editor@2.10.4 prebuild script 'npm run clean'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the swagger-editor package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run clean
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs swagger-editor
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls swagger-editor
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by bspeer-cs** [comment]
I ran npm start and it seems to be working.  Doesn't seem to interfere with functionality.

**Comment by saharj** [comment]
We are using Unix commands in `npm run clean` to delete dist folder. We should use something that works in windows too. [this](https://www.npmjs.com/package/rimraf) is a good solution. 

PR is welcome!

**Comment by webron** [comment]
This is no longer an issue with the new editor.
