### ISSUE TITLE
Doesnt work on Node >= 7

### ISSUE THREAD

**Issue by StarpTech** [swagger-api/swagger-editor#1210]
* Version: v2.10.5
* Browser/OS: 

**Issue**

```
I:\software\swagger-editor> npm install
loadDevDep:source-code-pr \ |##########################################################################################################----------------------------------------------------------------------------------------------------------------------------------------loadDevDep:source-code-pr | |##########################################################################################################----------------------------------------------------------------------------------------------------------------------------------------npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\Users\\dustin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v3.8.0

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     I:\software\swagger-editor\npm-debug.log
```

**Comment by kaizhu256** [comment]
i get the following error on latest node v7 on 2016/03/20:
https://travis-ci.org/npmdoc/node-npmdoc-swagger-editor/builds/212753154#L713

Cannot find module 'deepmerge'
Error: Cannot find module 'deepmerge'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/home/travis/build/npmdoc/node-npmdoc-swagger-editor/node_modules/swagger-editor/dist/swagger-editor.js:1:162)
    at Object.<anonymous> (/home/travis/build/npmdoc/node-npmdoc-swagger-editor/node_modules/swagger-editor/dist/swagger-editor.js:1:1186)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by webron** [comment]
This is not relevant with the new editor. Please follow the new build instructions.
