### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by moishy90** [swagger-api/swagger-editor#1227]
When I run npm install from the master branch

```
> v8-debug@0.7.7 preinstall /home/moshe/Developer/git_repos/swagger-editor/node_modules/.staging/v8-debug-3e5f80c7
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 preinstall /home/moshe/Developer/git_repos/swagger-editor/node_modules/.staging/v8-profiler-90c9f04b
> node -e 'process.exit(0)'

npm WARN prefer global node-inspector@0.12.8 should be installed with -g

> v8-debug@0.7.7 install /home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.3 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::Call(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:38:27: error: no matching function for call to ‘v8::Debug::Call(v8::Local<v8::Function>&)’
         v8::Debug::Call(fn);
                           ^
In file included from ../src/debug.cc:1:0:
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:198:28: note: candidate: static v8::MaybeLocal<v8::Value> v8::Debug::Call(v8::Local<v8::Context>, v8::Local<v8::Function>, v8::Local<v8::Value>)
   static MaybeLocal<Value> Call(Local<Context> context,
                            ^~~~
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:198:28: note:   candidate expects 3 arguments, 1 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::SendCommand(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:46:61: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Isolate* debug_isolate = v8::Debug::GetDebugContext()->GetIsolate();
                                                             ^
In file included from ../src/debug.cc:1:0:
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^~~~~~~~~~~~~~~
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE nodex::Debug::RunScript(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/debug.cc:61:67: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
         Local<Context> debug_context = v8::Debug::GetDebugContext();
                                                                   ^
In file included from ../src/debug.cc:1:0:
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^~~~~~~~~~~~~~~
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
../src/debug.cc:66:54: error: no matching function for call to ‘v8::Debug::GetDebugContext()’
           debug_context = v8::Debug::GetDebugContext();
                                                      ^
In file included from ../src/debug.cc:1:0:
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:248:25: note: candidate: static v8::Local<v8::Context> v8::Debug::GetDebugContext(v8::Isolate*)
   static Local<Context> GetDebugContext(Isolate* isolate);
                         ^~~~~~~~~~~~~~~
/home/moshe/.node-gyp/7.7.3/include/node/v8-debug.h:248:25: note:   candidate expects 1 argument, 0 provided
debug.target.mk:97: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1
make: Leaving directory '/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/moshe/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-41-generic
gyp ERR! command "/home/moshe/.nvm/versions/node/v7.7.3/bin/node" "/home/moshe/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64"
gyp ERR! cwd /home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/moshe/.nvm/versions/node/v7.7.3/bin/node /home/moshe/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/moshe/Developer/git_repos/swagger-editor/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.8.0-41-generic
node-pre-gyp ERR! command "/home/moshe/.nvm/versions/node/v7.7.3/bin/node" "/home/moshe/Developer/git_repos/swagger-editor/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug
node-pre-gyp ERR! node -v v7.7.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
Failed to execute '/home/moshe/.nvm/versions/node/v7.7.3/bin/node /home/moshe/.nvm/versions/node/v7.7.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64/debug.node --module_name=debug --module_path=/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-debug/build/debug/v0.7.7/node-v51-linux-x64' (1)

> v8-profiler@5.6.5 install /home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.6.5/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.6.5 and node@7.7.3 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/moshe/Developer/git_repos/swagger-editor/node_modules/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
^Cprofiler.target.mk:102: recipe for target 'Release/obj.target/profiler/src/cpu_profile.o' failed
make: *** [Release/obj.target/profiler/src/cpu_profile.o] Interrupt

```
I tried this from two ubuntu 16.10 installations from different networks

**Comment by moishy90** [comment]
This might be related to [this](https://github.com/swagger-api/swagger-editor/issues/1210)

**Comment by webron** [comment]
@moishy90 we need to update the README. The new version of the project can only be built with Node 6.

**Comment by moishy90** [comment]
Ah. yes. It works now. Thank you
