### ISSUE TITLE
A dot in either the model name, or a property name throws an error in WebWorker

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-editor#1395]
In the following spec, `desciption` should have a validation error, but because there is a dot in `One.Two` it simply throws an error in the conole. The error occurs in the WebWorker.

```yaml
swagger: '2.0'

info:
  version: 1.0.0
  title: Dot in Model name ( or properties, same applies )

definitions:
  One.Two:
    type: object
    desciption: this shoud be spelled "description"
```

> My guess is that its failing to de-reference the path, due to the dot.

`Object {swaggerEditor: "3.0.13/g9e127dc-dirty", swaggerUi: "3.0.17/g165c1d7"}`

Error: 
```
blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13 Worker caught an error: TypeError: Cannot read property '1' of null
    at blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:2:3541
    at Array.map (native)
    at i (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:2:3471)
    at blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:1:3446
    at Array.map (native)
    at i (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:1:3349)
    at blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:1:823
    at r (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13:22530)
    at i (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13:22586)
    at s (blob:http://editor.swagger.io/328489e7-9ef7-4ff2-887c-8f48b950feba:13:22835)
```
```
VM1555:27 Error: Cannot read property '1' of null
    at t._callbacks.(anonymous function) (http://editor.swagger.io/dist/swagger-editor-bundle.js:153:1596)
    at i (http://editor.swagger.io/dist/swagger-editor-bundle.js:153:1302)
    at Worker.<anonymous> (http://editor.swagger.io/dist/swagger-editor-bundle.js:153:1405)
```

**Comment by shockey** [comment]
Your guess is probably right - at some point I moved most of the codebase to using array paths, but there may be a few dot-delineated string paths running about.
