### ISSUE TITLE
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by rowshan** [swagger-api/swagger-editor#1743]
Hi here is my api file : 

`import datetime
import requests
#import re
import simplejson
from base64 import b64decode
from connexion import NoContent

raw_data = requests.get("http://172.18.0.2:8000/onem2m/MemsIPE/sensor_data/x/latest/")
#print raw_data
array = raw_data.content
print array
final_data = simplejson.loads(str(array))
print final_data
devices = b64decode(final_data["m2m:cin"]["con"])
print devices

#devices= final_data

def post(servicename):
    count = len(devices)
    print(count)
    servicename['id'] = count + 1
    servicename['registered'] = datetime.datetime.now()
    devices[servicename['device']] = servicename
    return servicename, 201

def put(id, servicename):
    id = str(id)
    if devices.get(id) is None:
        return NoContent, 404
    devices[id] = servicename

    return devices[id]

def delete(id):
    id = str(id)
    if devices.get(id) is None:
        return NoContent, 404
    del devices[id]
    return NoContent, 204

def get(id, servicename):
    id = str(id)
    if devices.get(id) is None:
        return NoContent, 404
    devices[id] = servicename
    return devices[id]

def search():
    # NOTE: we need to wrap it with list for Python 3 as dict_values is not JSON serializable
    return devices
`

here is the error:

> 
ERROR:connexion.api:Failed to add operation for GET /eds/devices
Traceback (most recent call last):
  File "eds.py", line 70, in <module>
    resolver=RestyResolver('api'))
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/app.py", line 149, in add_api
    debug=self.debug)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/api.py", line 154, in __init__
    self.add_paths()
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/api.py", line 251, in add_paths
    self._handle_add_operation_error(path, method, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/api.py", line 262, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/api.py", line 237, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/api.py", line 189, in add_operation
    resolver=self.resolver)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/operation.py", line 179, in __init__
    resolution = resolver.resolve(self)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/resolver.py", line 39, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/usr/local/lib/python2.7/dist-packages/connexion-1.0.129-py2.7.egg/connexion/utils.py", line 119, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sro/Desktop/final_eds/elastest-device-emulator-service/eds/rest_app/api/__init__.py", line 1, in <module>
    import  api.devices  # noqa
  File "/home/sro/Desktop/final_eds/elastest-device-emulator-service/eds/rest_app/api/devices.py", line 12, in <module>
    final_data = simplejson.loads(str(array))
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea how to overcome this .

| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  
| Which Swagger/OpenAPI version?      |
| Which Swagger-Editor version?       |
| How did you install Swagger-Editor? | 
| Which browser & version?            |
| Which operating system?             | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by shockey** [comment]
Hey @rowshan, I'm going to close this since I don't see anything related to Swagger-UI in your ticket - this is not the place to ask questions about other Swagger/OpenAPI tools, or the specification in general.
