### ISSUE TITLE
Generate Javascript client from editor (Swagger Hub) fails to generate a valid result

### ISSUE THREAD

**Issue by Cloudmersive** [swagger-api/swagger-editor#1754]
| Q                                   | A
| ----------------------------------- | -------
| Bug or feature request?             |  Bug
| Which Swagger/OpenAPI version?      | OpenAPI 2.0
| Which Swagger-Editor version?       | Latest on SwaggerHub
| How did you install Swagger-Editor? | Using SwaggerHub hosted version
| Which browser & version?            | Chrome - latest
| Which operating system?             | Windows 10 - latest

### Demonstration API definition

Full API definition here:

https://api.cloudmersive.com/specs/allapis.json

### Repro steps

1. Import into SwaggerHub/editor
2. Export Javascript client

### Expected Behavior
Generates a valid Javascript client

### Current Behavior
Generates an invalid Javascript client

Package fails to load on startup wtih this error:

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\...\Documents\Visual Studio 2017\Projects\NodejsWebApp5\NodejsWebApp5\server.js:3:20)

**Comment by shockey** [comment]
@Cloudmersive, I just generated a client from the definition that you linked to, and there's no `import` statements in it. Are you sure that you aren't mistakenly using `import` syntax in your project (maybe at `server.js:3:20`)?

**Comment by shockey** [comment]
Oops - didn't notice that you were seeing this in SwaggerHub.

Please reach out to SwaggerHub support, they can get this through the proper channels for you 😄

**Comment by shockey** [comment]
Closing due to inactivity. 

This is simply to keep our issue tracker clean - feel free to comment if there are any further thoughts or concerns, and we'll be happy to reopen this issue.
