### ISSUE TITLE
npm run build fails on xenial

### ISSUE THREAD

**Issue by annamel** [swagger-api/swagger-editor#1934]
npm run build fails

`root@swagger1:/home/swagger-editor# npm bugs swagger-editor
npm ERR! Linux 4.4.0
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "swagger-editor"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent `

`root@swagger1:/home/swagger-editor# cat /home/swagger-editor/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle swagger-editor@3.6.20~prebuild: swagger-editor@3.6.20
6 silly lifecycle swagger-editor@3.6.20~prebuild: no script for prebuild, continuing
7 info lifecycle swagger-editor@3.6.20~build: swagger-editor@3.6.20
8 verbose lifecycle swagger-editor@3.6.20~build: unsafe-perm in lifecycle true
9 verbose lifecycle swagger-editor@3.6.20~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/swagger-editor/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle swagger-editor@3.6.20~build: CWD: /home/swagger-editor
11 silly lifecycle swagger-editor@3.6.20~build: Args: [ '-c',
11 silly lifecycle   'run-p --aggregate-output build-core build-bundle build-standalone' ]
12 silly lifecycle swagger-editor@3.6.20~build: Returned: code: 1  signal: null
13 info lifecycle swagger-editor@3.6.20~build: Failed to exec build script
14 verbose stack Error: swagger-editor@3.6.20 build: `run-p --aggregate-output build-core build-bundle build-standalone`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid swagger-editor@3.6.20
16 verbose cwd /home/swagger-editor
17 error Linux 4.4.0
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error swagger-editor@3.6.20 build: `run-p --aggregate-output build-core build-bundle build-standalone`
22 error Exit status 1
23 error Failed at the swagger-editor@3.6.20 build script 'run-p --aggregate-output build-core build-bundle build-standalone'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the swagger-editor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     run-p --aggregate-output build-core build-bundle build-standalone
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs swagger-editor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls swagger-editor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by annamel** [comment]
[npm.log](https://github.com/swagger-api/swagger-editor/files/2780454/npm.log)

**Comment by MichakrawSB** [comment]
We’ve released Swagger Editor v5! 🎉 Check out the details here: [Inside the New Swagger Editor](https://swagger.io/blog/inside-the-new-swagger-editor/).
We’re closing old issues related to previous versions. If you think any of them are still relevant, please open a new issue – this helps us prioritize what matters most. Thanks for your activity! 🚀
