### ISSUE TITLE
Error when starting swagger-editor with npm (Windows)

### ISSUE THREAD

**Issue by hdvianna** [swagger-api/swagger-editor#2119]
I am not being able to start the swagger-editor (error log bellow):

```
PS %PROJECTS_PATH%\swagger-editor-master> npm start                                                                                                                                                        
> swagger-editor@3.8.0 prestart %PROJECTS_PATH%\swagger-editor-master
> npm install


> iltorb@2.4.3 install %PROJECTS_PATH%\swagger-editor-master\node_modules\iltorb
> node ./scripts/install.js || node-gyp rebuild

info looking for cached prebuild @ %APPDATA%\npm-cache\_prebuilds\d53d62-iltorb-v2.4.3-node-v72-win32-x64.tar.gz
http request GET https://github.com/MayhemYDG/iltorb/releases/download/v2.4.3/iltorb-v2.4.3-node-v72-win32-x64.tar.gz
http request Proxy setup detected (Host: *************, Port: *******, Authentication: *****) Tunneling with httpsOverHttp
WARN install self signed certificate in certificate chain

%PROJECTS_PATH%\swagger-editor-master\node_modules\iltorb>if not defined npm_config_node_gyp (node "%PROGRAMFILES%\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "%PROGRAMFILES%\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed:  %LOCALAPPDATA%\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "%PROGRAMFILES%\\nodejs\\node.exe" "%PROGRAMFILES%\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd %PROJECTS_PATH%\swagger-editor-master\node_modules\iltorb
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN The package deepmerge is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@2.4.3 install: `node ./scripts/install.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@2.4.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     %APPDATA%\npm-cache\_logs\2020-03-05T19_39_39_154Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-editor@3.8.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor@3.8.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     %APPDATA%\npm-cache\_logs\2020-03-05T19_39_39_302Z-debug.log
````

**Comment by hdvianna** [comment]
This issue is related to the use of self-chained certificate in the certifcate chain and not with swagger-editor. 
To fix it, you need to set the NODE_EXTRA_CA_CERTS enviroment variable with the path to your certificate.

For example,
`set NODE_EXTRA_CA_CERTS=c:\certs\ca.pem`
or
`export NODE_EXTRA_CA_CERTS=~/certs/ca.pem`

More info in: https://github.com/nodejs/node-gyp/issues/695
