### ISSUE TITLE
Jest: cross origin null forbidden

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-editor#2223]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: n/a
 - Version: n/a
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-Editor version: 3.12.0, but also observed in 3.11.0 during Jest development.
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

see Steps to reproduce.

This error is not visible in the browser

### Describe the bug you're encountering

This test file all passes, but will print errors to terminal.

```
Error: Cross origin null forbidden
        at dispatchError (/Users/timothy.lai/Repos/swagger-editor/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
        at Object.validCORSHeaders (/Users/timothy.lai/Repos/swagger-editor/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:74:5)
        at receiveResponse (/Users/timothy.lai/Repos/swagger-editor/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:796:19)
        at Request.<anonymous> (/Users/timothy.lai/Repos/swagger-editor/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:657:36)
        at Request.emit (events.js:321:20)
        at Request.onRequestResponse (/Users/timothy.lai/Repos/swagger-editor/node_modules/jest-environment-jsdom/node_modules/request/request.js:1059:10)
        at ClientRequest.emit (events.js:321:20)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
        at Socket.socketOnData (_http_client.js:479:22) undefined
```

### To reproduce...

1. Run Jest unit test at `/test/unit/plugins/validate-semantic/2and3/refs.js`
2. See error printed above.

### Expected behavior

No print errors

### Additional context or thoughts

This is likely a Jest issue with CORS.

**Comment by Fcmam5** [comment]
Hi @tim-lai I can take this issue ☝️
