### ISSUE TITLE
editor preview cannot handle path /

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-editor#239]
I pulled the latest swagger-editor from GitHub this morning and started it.

Using

```
swagger: "2.0"
info:
  title: Sample
  termsOfService: internal use only
  contact:
     name: David Biesack
     email: David.Biesack@sas.com
  license:
     name: Apache 2.0
     url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1"
host: mu.na.sas.com
basePath: /mu/rest
schemes: ["http"]

paths:
  /:
    get:
      description: |
        Return a list of links to the top level resources
        in this API, as well as links to create new instances
        in the top level collections.
      produces:
         - application/json
         - application/xml
      responses:
        200:
          description: links to the resource collections in this API
```

the preview operation for GET / does not work.
The Preview shows 

Request

GET undefined HTTP/1.1

and also does not present the media type selector for the Accept header.

The JavaScript console shows:

```
2
Error: [$interpolate:interr] Can't interpolate: {{generateUrl()}}
TypeError: Cannot read property 'reduce' of undefined
http://errors.angularjs.org/1.2.15/$interpolate/interr?p0=%7B%7BgenerateUrl…%7D&p1=TypeError%3A%20Cannot%20read%20property%20'reduce'%20of%20undefined
    at http://djb.na.sas.com:9000/bower_components/angular/angular.js:78:12
    at Object.$interpolate.fn (http://djb.na.sas.com:9000/bower_components/angular/angular.js:8421:26)
    at Scope.$digest (http://djb.na.sas.com:9000/bower_components/angular/angular.js:12023:40)
    at Scope.$apply (http://djb.na.sas.com:9000/bower_components/angular/angular.js:12279:24)
    at tick (http://djb.na.sas.com:9000/bower_components/angular/angular.js:8618:36) angular.js:9563
TypeError: Cannot read property 'map' of undefined
    at Scope.$scope.getRequestBody (http://djb.na.sas.com:9000/scripts/directives/tryoperation.js:103:29)
    at Object.get (http://djb.na.sas.com:9000/bower_components/angular/angular.js:10348:21)
    at Scope.$digest (http://djb.na.sas.com:9000/bower_components/angular/angular.js:12023:40)
    at Scope.$apply (http://djb.na.sas.com:9000/bower_components/angular/angular.js:12279:24)
    at tick (http://djb.na.sas.com:9000/bower_components/angular/angular.js:8618:36) angular.js:9563
2
Error: [$interpolate:interr] Can't interpolate: {{generateUrl()}}
TypeError: Cannot read property 'reduce' of undefined
http://errors.angularjs.org/1.2.15/$interpolate/interr?p0=%7B%7BgenerateUrl…%7D&p1=TypeError%3A%20Cannot%20read%20property%20'reduce'%20of%20undefined
    at http://djb.na.sas.com:9000/bower_components/angular/angular.js:78:12
    at Object.$interpolate.fn (http://djb.na.sas.com:9000/bower_components/angular/angular.js:8421:26)
    at Scope.$digest (http://djb.na.sas.com:9000/bower_components/angular/angular.js:12023:40)
    at Scope.$apply (http://djb.na.sas.com:9000/bower_components/angular/angular.js:12279:24)
    at done (http://djb.na.sas.com:9000/bower_components/angular/angular.js:7991:45)
    at completeRequest (http://djb.na.sas.com:9000/bower_components/angular/angular.js:8196:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://djb.na.sas.com:9000/bower_components/angular/angular.js:8137:11) 
```

If I export this to JSON, swagger-ui can correctly run the GET / 
(it shows the Request URL as http://mu.na.sas.com:80/mu/rest/ )
but it also does not have the Accept: selector from the media types
in the produces element.

**Comment by rocktmn1** [comment]
I am still getting this error when trying with this block

```json
swagger: "2.0"
info:
  description: |
    My Test Service

  version: "1.0.0"
  title: My Test Service
  contact:
    name: my.name@mycompany.com
host: servername.mycompany.com:9443
basePath: /myservice/api
schemes:
  - https
```

**Comment by mohsen1** [comment]
@rocktmn1 I don't see any error in editor.swagger.io with that block. If you're running a local copy, please update to latest
