### ISSUE TITLE
Problems setting up Vagrant dev box

### ISSUE THREAD

**Issue by gkjt** [swagger-api/swagger-editor#314]
I am currently trying to set up a Vagrant box in order to start contributing, but I am unable to get npm to start. I have tried reinstalling most things, redownloading the project, and looked at similar issues with no success.

To begin with, trying `vagrant up` into git shell starts things going, and it goes well up to npm, when it outputs my first attached output below. Some of it seems optional but the stuff on npm may be relevant.

After this it gets to the bower decompression, with most things green but several parts failing, until it gets to the end, where it outputs as in output 2. This appears to be a C funtion call failing, but I do not have the experience to tell for sure. This is the last output for `vagrant up`.

I can then `vagrant ssh` in without issue and it puts me straight into `/vagrant`. I try `npm start` and get output 3, which says it is an issue in `grunt dev:run`, confirmed by output 4 when I try `bower update` from the troubleshooting guide. Using `ls` however I can see the `Gruntfile.js`. I tried `bower clean` `bower install -f` too with the same effect.

`npm install` outputs as in output 5. I really cant see what I can do to fix it, so I would be grateful for any help. From what I can see, maybe the `node` and `npm` versions are too far updated from the project? 

My apologies for the length of this issue but I want to make sure the information is all here to see.

Output 1:
```
==> default: Installing HabitRPG
==> default: npm
==> default:
==> default: WARN
==> default: package.json
==> default:  karma-firefox-launcher@0.1.4 No README data
==> default: npm WARN
==> default: package.json karma-chrome-launcher@0.1.7 No README data
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: package.json
==> default:  icalendar@0.6.4 No repository field.
==> default: npm WARN
==> default:  package.json expect.js@0.2.0 No repository field.
==> default: npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"1.4.28"})
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: optional dep failed, continuing fsevents@0.2.1
==> default: npm
==> default:  WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"1.4.28"})
==> default: npm
==> default:
==> default: WARN
==> default:  engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"1.4.28"})
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: engine
==> default:  hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"1.4.28"})
==> default: npm WARN
==> default:  engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"1.4.28"})
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: package.json
==> default:  proxying-agent@0.1.5 'repositories' (plural) Not supported. Please pick one as the 'repository' field
==> default: npm
==> default:
==> default: WARN
==> default:
==> default: optional dep failed, continuing
==> default:  uglify-js@2.3.6
==> default: npm
==> default:
==> default: ERR! Error: UNKNOWN, symlink '../rimraf/bin.js'
==> default: npm
==> default: ERR!
==> default:  If you need help, you may report this *entire* log,
==> default: npm ERR! including the npm and node versions, at:
==> default: npm
==> default:  ERR!     <http://github.com/npm/npm/issues>
==> default: npm ERR! System Linux 3.2.0-23-generic
==> default: npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
==> default: npm ERR! cwd /vagrant
==> default: npm ERR! node -v
==> default:  v0.10.33
==> default: npm ERR! npm -v 1.4.28
==> default: npm ERR! path ../rimraf/bin.js
==> default: npm ERR!
==> default:
==> default: code UNKNOWN
==> default: npm ERR! errno
==> default:  -1
==> default: npm
==> default: ERR!
==> default: not ok code 0
```

Output 2:
```
==> default: bower angular-ui-select2#*                 ETXTBSY ETXTBSY, unlink '/vagrant/.bower-tmp/angular-ui-select2-
17747-EX0Lut/archive.tar.gz'
==> default:
==> default: Stack trace:
==> default: Error: ETXTBSY, unlink '/vagrant/.bower-tmp/angular-ui-select2-17747-EX0Lut/archive.tar.gz'
==> default:
==> default: Console trace:
==> default: Trace
==> default:     at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
==> default:     at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
==> default:     at Logger.emit (events.js:95:17)
==> default:     at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
==> default:     at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
==> default:     at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
==> default:     at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
==> default:     at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
==> default:     at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
==> default:     at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44
==> default:
==> default: System info:
==> default: Bower version: 1.3.12
==> default: Node version: 0.10.33
==> default: OS: Linux 3.2.0-23-generic x64
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Output 3:
```
vagrant@habitrpg:/vagrant$ npm start

> habitrpg@0.0.0-152 start /vagrant
> grunt run:dev

grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started

npm ERR! habitrpg@0.0.0-152 start: `grunt run:dev`
npm ERR! Exit status 99
npm ERR!
npm ERR! Failed at the habitrpg@0.0.0-152 start script.
npm ERR! This is most likely a problem with the habitrpg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt run:dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls habitrpg
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0
```

Output 4:

```
bower github-buttons#*                ETXTBSY ETXTBSY, unlink '/vagrant/.bower-tmp/github-buttons-17927-JwMvCf/archive.t
ar.gz'

Stack trace:
Error: ETXTBSY, unlink '/vagrant/.bower-tmp/github-buttons-17927-JwMvCf/archive.tar.gz'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.2.0-23-generic x64
vagrant@habitrpg:/vagrant$ grunt run:dev
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

Output 5:
```
npm WARN package.json icalendar@0.6.4 No repository field.
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN package.json karma-chrome-launcher@0.1.7 No README data
npm WARN package.json expect.js@0.2.0 No repository field.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.3.0"})
npm WARN optional dep failed, continuing fsevents@0.2.1
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.3.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.3.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.3.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.3.0"})
npm WARN package.json proxying-agent@0.1.5 'repositories' (plural) Not supported. Please pick one as the 'repository' fi
eld
npm WARN optional dep failed, continuing uglify-js@2.3.6
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.3.0
npm ERR! path ../rimraf/bin.js
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../rimraf/bin.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.3.0
npm ERR! path npm-debug.log.a558955dac4bcca93da58d5ba630320c
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.a558955dac4bcca93da58d5ba630320c'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

**Comment by gkjt** [comment]
Ok, apologies, I messed up

**Comment by cybercrash** [comment]
How did you fix this? I'm having similar issues.
