### ISSUE TITLE
Error on npm start, Ubuntu 12.04 64bit

### ISSUE THREAD

**Issue by roman-io** [swagger-api/swagger-editor#319]
Tried several times to install swagger-editor and it won't start

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded

npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/home/roman/.nvm/v0.10.35/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.8.2 start: `node start.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the swagger-editor-src@2.8.2 start script 'node start.js'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/roman/Projects/Swagger/swagger-api/swagger-editor/npm-debug.log
```

 /home/roman/Projects/Swagger/swagger-api/swagger-editor/npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/home/roman/.nvm/v0.10.35/bin/npm', 'start' ]
2 info using npm@2.2.0
3 info using node@v0.10.35
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart swagger-editor-src@2.8.2
6 verbose unsafe-perm in lifecycle true
7 info start swagger-editor-src@2.8.2
8 verbose unsafe-perm in lifecycle true
9 info swagger-editor-src@2.8.2 Failed to exec start script
10 verbose stack Error: swagger-editor-src@2.8.2 start: `node start.js`
10 verbose stack Exit status 7
10 verbose stack     at EventEmitter.<anonymous> (/home/roman/.nvm/v0.10.35/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/home/roman/.nvm/v0.10.35/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid swagger-editor-src@2.8.2
12 verbose cwd /home/roman/Projects/Swagger/swagger-api/swagger-editor
13 error Linux 3.13.0-44-generic
14 error argv "node" "/home/roman/.nvm/v0.10.35/bin/npm" "start"
15 error node v0.10.35
16 error npm  v2.2.0
17 error code ELIFECYCLE
18 error swagger-editor-src@2.8.2 start: `node start.js`
18 error Exit status 7
19 error Failed at the swagger-editor-src@2.8.2 start script 'node start.js'.
19 error This is most likely a problem with the swagger-editor-src package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node start.js
19 error You can get their info via:
19 error     npm owner ls swagger-editor-src
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

What can cause the issue?
Thanks

**Comment by mohsen1** [comment]
I just tried on Ubuntu 14 which shouldn't be too different than Ubuntu 12 in this case. It's working with no problem.
Please clean your npm cache by `npm cahce clean` and get the latest in master then try again. If it was still happening please re-open.
