### ISSUE TITLE
Using import gives error "unexpected token h"

### ISSUE THREAD

**Issue by tuukkamustonen** [swagger-api/swagger-editor#345]
Using latest master with only modification of setting `importProxyUrl` to `""`, as CORS headers are set by my server already:

    Access-Control-Allow-Origin: *
    Access-Control-Allow-Headers: Authorization, X-User-Uuid, X-Tenant-Id, Content-Type
    Access-Control-Allow-Methods: POST, GET, PUT, DELETE

Doing `http://localhost:9000/#/edit?import=http://localhost:8000/swagger.yaml` gives out stacktrace in chrome:

    SyntaxError: Unexpected token h
        at Object.parse (native)
        at fromJson (http://localhost:9000/bower_components/angular/angular.js:1066:14)
        at defaultHttpResponseTransform (http://localhost:9000/bower_components/angular/angular.js:8570:16)
        at http://localhost:9000/bower_components/angular/angular.js:8655:12
        at forEach (http://localhost:9000/bower_components/angular/angular.js:323:20)
        at transformData (http://localhost:9000/bower_components/angular/angular.js:8654:3)
        at transformResponse (http://localhost:9000/bower_components/angular/angular.js:9380:23)
        at processQueue (http://localhost:9000/bower_components/angular/angular.js:13175:27)
        at http://localhost:9000/bower_components/angular/angular.js:13191:27
        at Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:14388:28)

**Comment by tuukkamustonen** [comment]
Doh, I found https://github.com/swagger-api/swagger-ui/issues/412. My case was similar: I was returning yaml file with `application/json`. Changed the mimetype of `text/yaml` and now it works.

So, an invalid ticket, oopsie :/
