### ISSUE TITLE
Can't run the app localy

### ISSUE THREAD

**Issue by freiden** [swagger-api/swagger-editor#379]
Hi,
I've tried to run the editor locally following the README and I have the following it's failing on OSX 10.9 and 10.10:
Here are the logs files:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.6.0
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.2
7 verbose unsafe-perm in lifecycle true
8 info swagger-editor-src@2.9.2 Failed to exec prestart script
9 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm install`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid swagger-editor-src@2.9.2
11 verbose cwd /Users/charles/Devs/to_trash/swagger-editor
12 error Darwin 14.1.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.0
15 error npm  v2.6.0
16 error code ELIFECYCLE
17 error swagger-editor-src@2.9.2 prestart: `npm install`
17 error Exit status 1
18 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm install'.
18 error This is most likely a problem with the swagger-editor-src package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install
18 error You can get their info via:
18 error     npm owner ls swagger-editor-src
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
And the following on Ubuntu 14.04:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.2
7 verbose unsafe-perm in lifecycle true
8 info start swagger-editor-src@2.9.2
9 verbose unsafe-perm in lifecycle true
10 info swagger-editor-src@2.9.2 Failed to exec start script
11 verbose stack Error: swagger-editor-src@2.9.2 start: `grunt serve`
11 verbose stack Exit status 6
11 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1008:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
12 verbose pkgid swagger-editor-src@2.9.2
13 verbose cwd /home/vagrant/useful/swagger-editor
14 error Linux 3.13.0-46-generic
15 error argv "/usr/bin/node" "/usr/bin/npm" "start"
16 error node v0.12.0
17 error npm  v2.5.1
18 error code ELIFECYCLE
19 error swagger-editor-src@2.9.2 start: `grunt serve`
19 error Exit status 6
20 error Failed at the swagger-editor-src@2.9.2 start script 'grunt serve'.
20 error This is most likely a problem with the swagger-editor-src package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     grunt serve
20 error You can get their info via:
20 error     npm owner ls swagger-editor-src
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]
```
Here are the error displayed in terminals on OSX 10.9 and Ubuntu:
```
Running "less:server" (less) task
>> FileError: '../bower_components/bootstrap/less/bootstrap.less' wasn't found. Tried - app/bower_components/bootstrap/less/bootstrap.less,app/bower_components/bootstrap/less/bootstrap.less,../bower_components/bootstrap/less/bootstrap.less in app/styles/main.less on line 3, column 1:
>> 2
>> 3 @import (less) "../bower_components/bootstrap/less/bootstrap.less";
>> 4 @import (less) "../bower_components/json-formatter/dist/json-formatter.css";
Warning: Error compiling app/styles/main.less Use --force to continue.

Aborted due to warnings.
```
And on OSX 10.10:
```
unning "less:server" (less) task
>> FileError: '../bower_components/json-schema-view/dist/json-schema-view.css' wasn't found. Tried - app/bower_components/json-schema-view/dist/json-schema-view.css,app/bower_components/json-schema-view/dist/json-schema-view.css,../bower_components/json-schema-view/dist/json-schema-view.css in app/styles/main.less on line 5, column 1:
>> 4 @import (less) "../bower_components/json-formatter/dist/json-formatter.css";
>> 5 @import (less) "../bower_components/json-schema-view/dist/json-schema-view.css";
>> 6 @import (less) "../bower_components/angular-ui-layout/ui-layout.css";
Warning: Error compiling app/styles/main.less Use --force to continue.
```

Did I needed to install a package before running ```npm start```?

**Comment by brianjgeiger** [comment]
Running `bower install` will help; it does not appear to be installing bower components, which is what's missing here. I'm not sure if that will fix everything (I'm at the point where there's still some error that is causing my page to completely reload regularly losing some of my changes), but it will get you past that point.

**Comment by freiden** [comment]
I'm sort of newbie to the node world and I think it could be a great idea to indicate to install bower before executing the ```npm start```.

**Comment by mohsen1** [comment]
@freiden in `prestart` we're doing `bower install` now. The point is, we don't want users install Bower before using Swagger Editor

**Comment by wuweichi** [comment]
[root@localhost swagger-editor-master]# npm run bower-install

> swagger-editor-src@2.9.2 prebower-install /var/www/html/swagger-editor-master
> npm install


> swagger-editor-src@2.9.2 bower-install /var/www/html/swagger-editor-master
> bower install

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v0.12.1/bin/node" "/root/.nvm/versions/node/v0.12.1/bin/npm" "run" "bower-install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 bower-install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 bower-install script 'bower install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/swagger-editor-master/npm-debug.log
