### ISSUE TITLE
Cannot run locally (OS X)

### ISSUE THREAD

**Issue by jonathanwiesel** [swagger-api/swagger-editor#403]
After cloning and running `npm start` I get the following errors:

```
...
npm WARN deprecated grunt-bower-install@1.6.0: use grunt-wiredep instead
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.7.1"})
npm WARN peerDependencies The peer dependency mocha@* included from karma-mocha will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1

npm ERR! null == true
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1

npm ERR! null == true
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
...
```

Later below:
```
...
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonathanwiesel/Git/Others/swagger-editor/npm-debug.log

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "bower-install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 prebower-install: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 prebower-install script 'npm install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonathanwiesel/Git/Others/swagger-editor/npm-debug.log

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 prestart: `npm run bower-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 prestart script 'npm run bower-install'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bower-install
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jonathanwiesel/Git/Others/swagger-editor/npm-debug.log
```

And the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.2
7 verbose unsafe-perm in lifecycle true
8 info swagger-editor-src@2.9.2 Failed to exec prestart script
9 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm run bower-install`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid swagger-editor-src@2.9.2
11 verbose cwd /Users/jonathanwiesel/Git/Others/swagger-editor
12 error Darwin 14.0.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.0
15 error npm  v2.7.1
16 error code ELIFECYCLE
17 error swagger-editor-src@2.9.2 prestart: `npm run bower-install`
17 error Exit status 1
18 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm run bower-install'.
18 error This is most likely a problem with the swagger-editor-src package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run bower-install
18 error You can get their info via:
18 error     npm owner ls swagger-editor-src
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by mohsen1** [comment]
Can you do the following and see if it help?

```shell
npm cache clean
bower cache clean
rm -rf node_modules app/bower_components
npm start
```

**Comment by jonathanwiesel** [comment]
@mohsen1 that solved the issue. Thanks
