### ISSUE TITLE
Error running npm start

### ISSUE THREAD

**Issue by giraone** [swagger-api/swagger-editor#424]
I just did a git clone and started `npm start` on a Windows 8.1 system. But I got the following error:

```
$ npm start

> swagger-editor-src@2.9.2 prestart C:\Tools\REST\swagger-editor
> npm run build


> swagger-editor-src@2.9.2 prebuild C:\Tools\REST\swagger-editor
> npm run bower-install


> swagger-editor-src@2.9.2 prebower-install C:\Tools\REST\swagger-editor
> npm install

npm WARN package.json karma-firefox-launcher@0.1.4 No README data
npm WARN package.json karma-mocha@0.1.10 No README data

> swagger-editor-src@2.9.2 bower-install C:\Tools\REST\swagger-editor
> bower install


> swagger-editor-src@2.9.2 build C:\Tools\REST\swagger-editor
> grunt build

Loading "htmlmin.js" tasks...ERROR
>> Error: Cannot find module 'chalk'
Loading "less.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
Warning: Task "less" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-05-04 21:54:52 UTC)
loading tasks  16ms  ███████████████████████████████████████████████████████████████████ 100%
Total 16ms


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 build: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 build script 'grunt build'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Tools\REST\swagger-editor\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\b
in\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.2 prestart: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-editor-src@2.9.2 prestart script 'npm run build'.
npm ERR! This is most likely a problem with the swagger-editor-src package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls swagger-editor-src
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Tools\REST\swagger-editor\npm-debug.log
$
```

Content of npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart swagger-editor-src@2.9.2
6 verbose unsafe-perm in lifecycle true
7 info swagger-editor-src@2.9.2 Failed to exec prestart script
8 verbose stack Error: swagger-editor-src@2.9.2 prestart: `npm run build`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
8 verbose stack     at EventEmitter.emit (events.js:110:17)
8 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
8 verbose stack     at ChildProcess.emit (events.js:110:17)
8 verbose stack     at maybeClose (child_process.js:1015:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
9 verbose pkgid swagger-editor-src@2.9.2
10 verbose cwd C:\Tools\REST\swagger-editor
11 error Windows_NT 6.3.9600
12 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error node v0.12.2
14 error npm  v2.7.4
15 error code ELIFECYCLE
16 error swagger-editor-src@2.9.2 prestart: `npm run build`
16 error Exit status 1
17 error Failed at the swagger-editor-src@2.9.2 prestart script 'npm run build'.
17 error This is most likely a problem with the swagger-editor-src package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm run build
17 error You can get their info via:
17 error     npm owner ls swagger-editor-src
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```

**Comment by mohsen1** [comment]
I believe your `npm install` was failed in your machine according to this:

```
>> Error: Cannot find module 'chalk'
Loading "less.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
```. 

Please delete your `node_modules` folder and run `npm start` again

**Comment by mohsen1** [comment]
I tested the latest in my Window VM. I suggest you use Git Bash instead of Windows CLI or make sure you have `git` and `node` in your PATH.

Here is the latest (c848614) running on Windows 8.1

![screen shot 2015-05-07 at 3 43 17 pm](https://cloud.githubusercontent.com/assets/543633/7527438/f52f62a0-f4cf-11e4-9e1b-4fc593b92764.png)

**Comment by hnjoshi** [comment]
@mohsen1  thank your for your solution about deleting node_module folder and try 'npm start' again. I had same issue and it got resolve...
