### ISSUE TITLE
npm won't start

### ISSUE THREAD

**Issue by BobWall23** [swagger-api/swagger-editor#465]
With this afternoon's commits, `npm start`  coughs up this npm_debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.6
7 verbose unsafe-perm in lifecycle true
8 info start swagger-editor-src@2.9.6
9 verbose unsafe-perm in lifecycle true
10 info swagger-editor-src@2.9.6 Failed to exec start script
11 verbose stack Error: swagger-editor-src@2.9.6 start: `grunt serve:dist`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1015:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
12 verbose pkgid swagger-editor-src@2.9.6
13 verbose cwd /Users/bob/3rdParty/swagger-editor
14 error Darwin 14.3.0
15 error argv "node" "/usr/local/bin/npm" "start"
16 error node v0.12.2
17 error npm  v2.7.5
18 error code ELIFECYCLE
19 error swagger-editor-src@2.9.6 start: `grunt serve:dist`
19 error Exit status 1
20 error Failed at the swagger-editor-src@2.9.6 start script 'grunt serve:dist'.
20 error This is most likely a problem with the swagger-editor-src package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     grunt serve:dist
20 error You can get their info via:
20 error     npm owner ls swagger-editor-src
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]
```

**Comment by mohsen1** [comment]
Please clean up your `node_modules` and `app/bower_components` folders and try again:

```shell
rm -rf node_modules app/bower_components
npm start
```

Let me know if it's still not working

**Comment by BobWall23** [comment]
Removing node_modules and app/bower_components didn’t help - same error.

**Comment by mohsen1** [comment]
Do you have grunt and bower installed globally? If so, please update them

**Comment by BobWall23** [comment]
Nope - neither was installed globally.

% which grunt
grunt not found
% which bower
bower not found

**Comment by BobWall23** [comment]
When I stopped npm to restart it after I pulled the new release, something didn't get stopped properly, apparently. Grunt was running in the background and had port 8080 open. No error in the log, but I finally saw it somewhere in the pile of output when trying to start npm. After killing grunt, npm was able to start properly. Sorry for the hassle.
