### ISSUE TITLE
Error while trying to start editor

### ISSUE THREAD

**Issue by Hantsch** [swagger-api/swagger-editor#566]
Hello,
i am allays getting this error when i try to install the editor like described on
http://swagger.io/swagger-editor/.

Log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart swagger-editor-src@2.9.6
7 verbose unsafe-perm in lifecycle true
8 info start swagger-editor-src@2.9.6
9 verbose unsafe-perm in lifecycle true
10 info swagger-editor-src@2.9.6 Failed to exec start script
11 verbose stack Error: swagger-editor-src@2.9.6 start: `grunt serve:dist`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1015:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
12 verbose pkgid swagger-editor-src@2.9.6
13 verbose cwd C:\rebn\entw\swagger-editor
14 error Windows_NT 6.1.7601
15 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
16 error node v0.12.2
17 error npm  v2.7.4
18 error code ELIFECYCLE
19 error swagger-editor-src@2.9.6 start: `grunt serve:dist`
19 error Exit status 1
20 error Failed at the swagger-editor-src@2.9.6 start script 'grunt serve:dist'.
20 error This is most likely a problem with the swagger-editor-src package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     grunt serve:dist
20 error You can get their info via:
20 error     npm owner ls swagger-editor-src
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]
```

**Comment by mohsen1** [comment]
Try cleaning up node modules and starting again. I've seen this error in Windows reported here many times. Look at other issues like #270 #216 #407 to find more help.

**Comment by mohsen1** [comment]
Also see my comment here: https://github.com/swagger-api/swagger-editor/issues/535#issuecomment-123795690
