### ISSUE TITLE
Editor error when running locally

### ISSUE THREAD

**Issue by jonbuck16** [swagger-api/swagger-editor#739]
I am trying to run the editor locally and I am running into some issues and would appreciate some pointers...

I have downloaded the latest version (2.9.8) at this point and have extracted the contents of the zip file into the root of my local webserver (Caddy).

When I try to load the editor using the url: http://localhost:2015/swagger-editor/ I am getting a blank page, however when I look at the console I am seeing the following error:

Warn: could not find module util vendor.js:51
ReferenceError: Map is not defined
    at new YAMLWorker (http://localhost:2015/swagger-editor/scripts/vendor.js:65:31737)
    at new YAML (http://localhost:2015/swagger-editor/scripts/scripts.js:1181:3519)
    at invoke (http://localhost:2015/swagger-editor/scripts/vendor.js:7:13109)
    at Object.instantiate (http://localhost:2015/swagger-editor/scripts/vendor.js:7:13275)
    at Object.<anonymous> (http://localhost:2015/swagger-editor/scripts/vendor.js:7:10438)
    at Object.invoke (http://localhost:2015/swagger-editor/scripts/vendor.js:7:13109)
    at Object.enforcedReturnValue [as $get] (http://localhost:2015/swagger-editor/scripts/vendor.js:7:10043)
    at Object.invoke (http://localhost:2015/swagger-editor/scripts/vendor.js:7:13109)
    at http://localhost:2015/swagger-editor/scripts/vendor.js:7:9296
    at getService (http://localhost:2015/swagger-editor/scripts/vendor.js:7:12469) <div class="total-wrapper ng-scope" ui-view=""> vendor.js:10

Any ideas why this is not working out of the box??

**Comment by saharj** [comment]
I am not able to reproduce this.
