### ISSUE TITLE
a definition renders as "undefined" in UI

### ISSUE THREAD

**Issue by gabrielsroka** [swagger-api/swagger-editor#800]
i have a definition:
~~~yaml
definitions:
  ProfileCredentials:
    type: object
    properties:
      profile:
        $ref: "#/definitions/Profile"
  Profile:
    type: object
    properties:
      login:
        type: string
~~~
but the editor renders the `ProfileCredentials.profile` as `undefined`. if i change it from `ProfileCredentials` to `ProfilCredentials`, it renders correctly. it's as if the substring match between `Profile` and `ProfileCredentials` is confusing it

Chrome dev console shows:
~~~
Error composing AST while scanning a simple key
  on line 120, column 3
could not find expected ':'
  on line 121, column 9
    at b.c [as constructor] (http://editor.swagger.io/scripts/vendor.js:35:30251)
    at b.c [as constructor] (http://editor.swagger.io/scripts/vendor.js:35:30538)
    at new b (http://editor.swagger.io/scripts/vendor.js:37:25539)
    at d.Scanner.a.stale_possible_simple_keys (http://editor.swagger.io/scripts/vendor.js:37:28622)
    at d.Scanner.a.need_more_tokens (http://editor.swagger.io/scripts/vendor.js:37:26829)
    at d.Scanner.a.check_token (http://editor.swagger.io/scripts/vendor.js:37:26247)
    at d.Parser.a.parse_block_sequence_entry (http://editor.swagger.io/scripts/vendor.js:38:21876)
    at d.Parser.a.check_event (http://editor.swagger.io/scripts/vendor.js:38:16139)
    at d.Composer.a.compose_sequence_node (http://editor.swagger.io/scripts/vendor.js:36:2589)
    at d.Composer.a.compose_node (http://editor.swagger.io/scripts/vendor.js:36:1953)
~~~

**Comment by saharj** [comment]
This issue was fixed [here](https://github.com/swagger-api/swagger-editor/pull/787). I just deployed it to editor.swagger.io/
