### ISSUE TITLE
Undefined/erratic behaviour on stray tab characters in YAML

### ISSUE THREAD

**Issue by IsoLinearCHiP** [swagger-api/swagger-editor#802]
When accidentally typing a double space after `description:` in a parameter declaration, various things stop working properly. 

- The absence of a path parameter suddendly triggers the warning banner instead of an error
- the jump to yaml links stop working
- the editor get unresponsive in large documents, as it is spewing thousands of exceptions.

The initial exception shown in the console is:

```
positionRangeForPath error: TypeError: Cannot read property 'tag' of undefined
    at i (http://editor.swagger.io/scripts/scripts.js:2:4796)
    at http://editor.swagger.io/scripts/scripts.js:2:5100
    at compose (http://editor.swagger.io/scripts/scripts.js:2:14860)
    at c (http://editor.swagger.io/scripts/scripts.js:2:4754)
    at http://editor.swagger.io/scripts/scripts.js:2:6255
    at positionRangeForPath (http://editor.swagger.io/scripts/scripts.js:2:6231)
    at i (http://editor.swagger.io/scripts/scripts.js:1:16457)
    at Array.map (native)
    at f (http://editor.swagger.io/scripts/scripts.js:1:15776)
    at Object.e [as fn] (http://editor.swagger.io/scripts/scripts.js:1:15509)(anonymous function) @ vendor.js:5(anonymous function) @ scripts.js:2
vendor.js:5 positionRangeForPath error: TypeError: Cannot read property 'tag' of undefined
    at i (http://editor.swagger.io/scripts/scripts.js:2:4796)
    at http://editor.swagger.io/scripts/scripts.js:2:5100
    at compose (http://editor.swagger.io/scripts/scripts.js:2:14860)
    at c (http://editor.swagger.io/scripts/scripts.js:2:4754)
    at http://editor.swagger.io/scripts/scripts.js:2:6255
    at positionRangeForPath (http://editor.swagger.io/scripts/scripts.js:2:6231)
    at i (http://editor.swagger.io/scripts/scripts.js:1:16457)
    at Array.map (native)
    at f (http://editor.swagger.io/scripts/scripts.js:1:15776)
    at e (http://editor.swagger.io/scripts/scripts.js:1:15509)(anonymous function) @ vendor.js:5(anonymous function) @ scripts.js:2
```

This behaviour is a bit wonky to reproduce, following steps seem to have triggered the bug:

- using chrome
- start inkognito mode, to ensure there is no initial state
- go to `http://editor.swagger.io/`
- delete the contets of the left pane
- note the `Emtpy Document Error`, as expected
- open the js console
- paste the following code:

```
swagger: '2.0'
info:
  title: Minimal test
  version: "1.0.0"

paths:
  /{test}:
    get:
      parameters:
        - name: foo
          in: query
          description: 	Note the double space here
          #           ^^ 
          # so this is a space followed by a tab character
          type: integer
      responses:
        default:
          description: Unexpected error
```

- pay attention to the fact, that there is a tab character after the space on the `description:` line, while I did paste it into the issue, it might get lost when copy and pasting from viewing the issue
- notice the exceptions and the `Emtpy Document Error`, it should be complaining about the missing parameter
- delete one of the curly brackets in line 7, as a quick and dirty fix for the validation error
- notice, no errors
- undo your change
- notice an empty warning banner and multiple exceptions
- delete the bracket again and this time delete the extra space as well
- reinsert the bracket
- notice the correct `Swagger Error: Path parameter is declared but is not defined: test`
- delete the bracket and then reinsert the extra space, in order to trigger the bug again ( at least so I thought )
- insert the bracket again
- notice the correct error and the absence of any exceptions ( no clue why it suddenly works then )

Freaking nightmare to reproduce.... took hours to narrow it down to this weird behaviour

**Comment by IsoLinearCHiP** [comment]
Doh.... Ok, it's not a double space, I just noticed. Its a stray tab character. At least that explains the last part of the behaviour.

**Comment by saharj** [comment]
I can not reproduce this issue. Can you please try again to see if you still see this?
