### ISSUE TITLE
Swagger Editor wont start

### ISSUE THREAD

**Issue by td-gonzales** [swagger-api/swagger-editor#837]
I have updated my Node and npm versions but I'm still getting ELIFECYCLE
```
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! swagger-editor-src@2.9.8 prestart: `npm run build`
npm ERR! Exit status 1

Since I can't upload the log file here it is:

$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.5
3 info using node@v5.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle swagger-editor-src@2.9.8~prestart: swagger-editor-src@2.9.8
6 verbose lifecycle swagger-editor-src@2.9.8~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle swagger-editor-src@2.9.8~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/tdgonzales/code/swagger-editor/node_modules/.bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/heroku/bin:/usr/local/heroku/bin
8 verbose lifecycle swagger-editor-src@2.9.8~prestart: CWD: /Users/tdgonzales/code/swagger-editor
9 silly lifecycle swagger-editor-src@2.9.8~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle swagger-editor-src@2.9.8~prestart: Returned: code: 1  signal: null
11 info lifecycle swagger-editor-src@2.9.8~prestart: Failed to exec prestart script
12 verbose stack Error: swagger-editor-src@2.9.8 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
12 verbose stack     at emitTwo (events.js:100:13)
12 verbose stack     at EventEmitter.emit (events.js:185:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:100:13)
12 verbose stack     at ChildProcess.emit (events.js:185:7)
12 verbose stack     at maybeClose (internal/child_process.js:827:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid swagger-editor-src@2.9.8
14 verbose cwd /Users/tdgonzales/code/swagger-editor
15 error Darwin 15.2.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 error node v5.7.0
18 error npm  v3.7.5
19 error code ELIFECYCLE
20 error swagger-editor-src@2.9.8 prestart: `npm run build`
20 error Exit status 1
21 error Failed at the swagger-editor-src@2.9.8 prestart script 'npm run build'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the swagger-editor-src package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run build
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs swagger-editor-src
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls swagger-editor-src
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by saharj** [comment]
Have you tried deleting your `node_modules` folder and trying `npm start` again? 

If you are looking to build Swagger Editor you can use the latest build from [releases](https://github.com/swagger-api/swagger-editor/releases) directly

**Comment by td-gonzales** [comment]
@saharj: I deleted everything in my global node_modules then reinstalled node which seemed to fix the problem.
