### ISSUE TITLE
swagger project not working

### ISSUE THREAD

**Issue by rakesh190** [swagger-api/swagger-editor#863]
Hello, I have created a node project using swagger, when I copied the project directory and pasted in another location, it is throwing me some errors. Here are the errors:

Starting: C:\workspace\entitlement-decision-service\app.js...
  project started here: http://localhost:10010/v1.0
  project will restart on changes.
  to restart at any time, enter `rs`
module.js:327
    throw err;
    ^

Error: Cannot find module 'delayed-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\workspace\entitlement-decision-service\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\node_modules\superagent\node_modules\form-data\node_modul
es\combined-stream\lib\combined_stream.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Could someone let me know how to fix this issue.

Thanks.

**Comment by saharj** [comment]
This issue was moved to swagger-api/swagger-node#365
