### ISSUE TITLE
Swagger Editor (and UI) not working under IE11

### ISSUE THREAD

**Issue by Winterwind83** [swagger-api/swagger-editor#874]
The Editor doesn't load for me under IE11 at all, the page stays completely white. If I go into debugging, In the console, the following message appears:
`Warn: could not find module util
ReferenceError: "Promise" is undefined
   at s (http://editor.swagger.io/dist/bundle.js:114:25662)
   at h (http://editor.swagger.io/dist/bundle.js:124:28454)
   at Anonymous function (http://editor.swagger.io/dist/bundle.js:124:28675)
   at s (http://editor.swagger.io/dist/bundle.js:32:20765)
   at Anonymous function (http://editor.swagger.io/dist/bundle.js:33:14017)
   at Anonymous function (http://editor.swagger.io/dist/bundle.js:78:23709)
   at fe (http://editor.swagger.io/dist/bundle.js:33:9355)
   at f (http://editor.swagger.io/dist/bundle.js:33:1759)
   at s (http://editor.swagger.io/dist/bundle.js:32:29963)
   at Anonymous function (http://editor.swagger.io/dist/bundle.js:32:29452) <div class="total-wrapper" ui-view="">
Warn: could not find module util`

The Petstore example won't load, either - the initial text ("This is a sample server Petstore server... ") and the links to Swagger and Apache show up, but nothing beyond them.

With Chrome, everything works fine.

**Comment by owenconti** [comment]
Hi @Winterwind83 

Just so you are aware, I have an open PR to fix the issue in IE 10 and 11. There is a separate issue (having to do with WebWorkers) that prevents IE <9 from working.

Link to the open PR: https://github.com/swagger-api/swagger-editor/pull/877
