### ISSUE TITLE
Example code doesn't work with swagger-codegen

### ISSUE THREAD

**Issue by tylerlong** [swagger-api/swagger-editor#879]
Go to http://editor.swagger.io/

Menu --> File --> Open examples --> twitter.yaml

Menu --> File --> Download YAML, the file was saved as swagger.yaml

```
wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l csharp -o /tmp/test
```

Error message:

```
LMXMN061:Downloads tyler.liu$ java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l csharp -o /tmp/test
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yaml
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
Exception in thread "main" java.lang.RuntimeException: Could not process model 'inline_response_200_3'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:244)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.languages.AbstractCSharpCodegen.getSwaggerType(AbstractCSharpCodegen.java:459)
	at io.swagger.codegen.DefaultCodegen.getTypeDeclaration(DefaultCodegen.java:862)
	at io.swagger.codegen.languages.AbstractCSharpCodegen.getTypeDeclaration(AbstractCSharpCodegen.java:482)
	at io.swagger.codegen.languages.AbstractCSharpCodegen.getTypeDeclaration(AbstractCSharpCodegen.java:475)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1247)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2232)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2206)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2193)
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1013)
	at io.swagger.codegen.languages.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:273)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:799)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:237)
	... 2 more
```

The issue is either about swagger-codegen or example of swagger-editor.

**Comment by saharj** [comment]
We have realized that there is a problem with twitter.yaml example. Do you have this issue with other example files as well?

**Comment by tylerlong** [comment]
@saharj yes, I tested several yesterday. instagram.yaml has this issue too. Actually I was unable to get any of the examples working.

**Comment by saharj** [comment]
This issue was moved to swagger-api/swagger-codegen#2680
